services:
  nginx:
    container_name: nginx

    build:
      context: ./requirements/nginx

    depends_on:
      - wordpress

    ports:
      - "443:443"

    volumes:
      - wordpress_data:/var/www/html

    restart: always

    networks:
      - pbotargu_net

  mariadb:
    container_name: mariadb

    build:
      context: ./requirements/mariadb

    volumes:
      - mariadb_data:/var/lib/mysql

    restart: always

    env_file:
      - .env

    networks:
      - pbotargu_net

  wordpress:
    container_name: wordpress

    build:
      context: ./requirements/wordpress

    depends_on:
      - mariadb

    volumes:
      - wordpress_data:/var/www/html

    restart: always

    env_file:
      - .env

    networks:
      - pbotargu_net

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: "/home/pbotargu/data/mariadb"
      o: bind
      type: none

  wordpress_data:
    driver: local
    driver_opts:
      device: "/home/pbotargu/data/wordpress"
      o: bind
      type: none


networks:
  pbotargu_net:
    name: pbotargu_net
    driver: bridge

